export const USER_LOADING='USER_LOADING';
export const USER_LOADED='USER_LOADED';
export const GET_ERRORS='GET_ERRORS';
export const CLEAR_ERRORS='CLEAR_ERRORS';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const AUTH_ERRORS='AUTH_ERRORS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const REGISTER_FAIL='REGISTER_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';

export const GET_PROFILE='GET_PROFILE';
export const CLEAR_PROFILE='CLEAR_PROFILE';
export const GET_ERRORS_PROFILE='GET_ERRORS_PROFILE';
export const ADDOREDIT_PROFILE='ADDOREDIT_PROFILE';
export const LOADING='LOADING';
export const SET_ALERT='SET_ALERT'
export const CLEAR_ALERT='CLEAR_ALERT';
export const GETALL_PROFILE='GETALL_PROFILE';
export const DELETE_ALL='DELETE_ALL';
export const GETALL_POST='GETALLPOST';
export const DELETE_POST='DELETE_POST';
export const GET_LIKES='GET_LIKES';
export const CLEAR_LIKES='CLEAR_LIKES';
export const ADD_POST='ADD_POST';
export const GET1POST='GET1POST';
export const ADD_COMMENT='ADD_COMMENT'
export const DELETE_COMMENT='DELETE_COMMENT'






