const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const PostSchema=new Schema({
    user:{
        type:Schema.Types.ObjectId,
        ref:'user'
    },
    name:{
        type:String
    },
    email:{
        type:String,
    },
    avatar:{
        type:String
    },
    text:{
        type:String,
        required:true
    },
    likes:[
        {
            user:{
                type:Schema.Types.ObjectId,
                ref:'user'
            },
            name:{
                type:String
            }
        }
    ]
        
    ,
    comments:[
        {
            user:{
                type:Schema.Types.ObjectId,
                ref:'user'
            },
            text:{
                type:String,
                require:true
            },
            name:{
                type:String,
                require:true
            },
            avatar:{
                type:String
            },
            date:{
                type:Date,
                default:Date.now
            }
        }
    ]
        
    ,
    date:{
        type:Date,
        default:Date.now
    }
});
module.exports=Post=mongoose.model('post',PostSchema);