const mongoose=require('mongoose');
const ProfileSchema=new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    Name:{
        type:String,
        required:true,
    },
    Gender:{
        type:String,
        required:true
    },
    Company:{
        type:String
    },
    Location:{
        type:String
    },
    Bio:{
        type:String,
      
    },
    Status:{
        type:String,
      
    },
    Country:{
        type:String,
        required:true
    },
    Skills:{
        type:[String],
       // required:true
    },
    experience:[
       {
           title:{
               type:String,
               require:true
           },
           company:{
               type:String,
               require:true,
           },
           location:{
               type:String
           },
           from:{
               type:Date,
               required:true
           },
           to:{
               type:Date
           },
           current:{
               type:Boolean,
               default:false
           },
           description:{
               type:String
           }
       }
    ],
    education:[
        {
            school:{
                type:String,
                require:true
            },
            degree:{
                type:String,
                require:true
            },
            fieldofstudy:{
                type:String,
                require:true
            },
            from:{
                type:Date,
                require:true
            },
            to:{
                type:Date,
               // require:true
            },
            current:{
                type:Boolean,
               // require:true
            },
            decription:{
                type:String
            }

        }
    ],
    social:[
        {
            youtube:{
                type:String
            },
            twitter:{
                type:String
            },
            facebook:{
                type:String
            },
            linkedin:{
                type:String
            },
            instagram:{
                type:String
            }
        }
    ],
    date:{
        type:Date,
        default:Date.now
    }

});
module.exports=Profile=mongoose.model('profile',ProfileSchema);